import { IPet, IPost } from '@/configs/interface';

export const homePageData = {
    impactOfYear: [
        {
            image: 'dog.svg',
            quantity: '2,000',
            title: 'Total pets fostered',
        },
        {
            image: 'cats.svg',
            quantity: '$12,000',
            title: 'In products  & donations',
            prefix: '$',
        },
        {
            image: 'home-dog.svg',
            quantity: '1,800',
            title: 'Total pets have a home',
        },
    ],
    pets: [
        {
            id: 1,
            breed: 'husky',
            name: 'lokbok',
            image: 'https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcQkrjYxSfSHeCEA7hkPy8e2JphDsfFHZVKqx-3t37E4XKr-AT7DML8IwtwY0TnZsUcQ',
            description: `The dog was hit by a car, broke his leg, and lost his eye for 2-3 days at an intersection`,
            fostered: '12/09/2022',
            size: 'medium',
            sex: 'male',
            type: 'dog',
            fosterDate: 300,
            like: true,
        },
        {
            id: 2,
            breed: 'husky',
            name: 'lokbok',
            image: 'https://ichef.bbci.co.uk/news/976/cpsprodpb/17638/production/_124800859_gettyimages-817514614.jpg',
            description: `The dog was hit by a car, broke his leg, and lost his eye for 2-3 days at an intersection`,
            fostered: '12/09/2022',
            size: 'medium',
            sex: 'male',
            type: 'dog',
            fosterDate: 300,
            like: true,
        },
        {
            id: 3,
            breed: 'husky',
            name: 'lokbok',
            image: 'https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcQkrjYxSfSHeCEA7hkPy8e2JphDsfFHZVKqx-3t37E4XKr-AT7DML8IwtwY0TnZsUcQ',
            description: `The dog was hit by a car, broke his leg, and lost his eye for 2-3 days at an intersection`,
            fostered: '12/09/2022',
            size: 'medium',
            sex: 'male',
            type: 'dog',
            fosterDate: 300,
            like: true,
        },
        {
            id: 4,
            breed: 'husky',
            name: 'lokbok',
            image: 'https://ichef.bbci.co.uk/news/976/cpsprodpb/17638/production/_124800859_gettyimages-817514614.jpg',
            description: `The dog was hit by a car, broke his leg, and lost his eye for 2-3 days at an intersection`,
            fostered: '12/09/2022',
            size: 'medium',
            sex: 'male',
            type: 'dog',
            fosterDate: 300,
            like: true,
        },
        {
            id: 5,
            breed: 'husky',
            name: 'lokbok',
            image: 'https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcQkrjYxSfSHeCEA7hkPy8e2JphDsfFHZVKqx-3t37E4XKr-AT7DML8IwtwY0TnZsUcQ',
            description: `The dog was hit by a car, broke his leg, and lost his eye for 2-3 days at an intersection`,
            fostered: '12/09/2022',
            size: 'medium',
            sex: 'male',
            type: 'dog',
            fosterDate: 300,
            like: true,
        },
        {
            id: 6,
            breed: 'husky',
            name: 'lokbok',
            image: 'https://ichef.bbci.co.uk/news/976/cpsprodpb/17638/production/_124800859_gettyimages-817514614.jpg',
            description: `The dog was hit by a car, broke his leg, and lost his eye for 2-3 days at an intersection`,
            fostered: '12/09/2022',
            size: 'medium',
            sex: 'male',
            type: 'dog',
            fosterDate: 300,
            like: false,
        },
        {
            id: 7,
            breed: 'husky',
            name: 'lokbok',
            image: 'https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcQkrjYxSfSHeCEA7hkPy8e2JphDsfFHZVKqx-3t37E4XKr-AT7DML8IwtwY0TnZsUcQ',
            description: `The dog was hit by a car, broke his leg, and lost his eye for 2-3 days at an intersection`,
            fostered: '12/09/2022',
            size: 'medium',
            sex: 'male',
            type: 'dog',
            fosterDate: 300,
            like: true,
        },
        {
            id: 8,
            breed: 'husky',
            name: 'lokbok',
            image: 'https://ichef.bbci.co.uk/news/976/cpsprodpb/17638/production/_124800859_gettyimages-817514614.jpg',
            description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit non nulla doloremque at dolorem libero ut, sequi nam explicabo iste maxime beatae, magnam facere aut fuga laudantium amet tenetur consectetur esse minima molestiae. Quam, sit quis doloribus saepe provident sapiente?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit non nulla doloremque at dolorem libero ut, sequi nam explicabo iste maxime beatae, magnam facere aut fuga laudantium amet tenetur consectetur esse minima molestiae. Quam, sit quis doloribus saepe provident sapiente?`,
            fostered: '12/09/2022',
            size: 'medium',
            sex: 'male',
            type: 'dog',
            fosterDate: 300,
            like: false,
        },
    ] as IPet[],
    postsPreview: [
        {
            id: 1,
            title: 'TITLE GOES HERE',
            // contents:
            //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit non nulla doloremque at dolorem libero ut, sequi nam explicabo iste maxime beatae, magnam facere aut fuga laudantium amet tenetur consectetur ',
            thumbnail:
                'https://www.scotsman.com/webimg/b25lY21zOmYxYmQ2NGNjLTIwNTYtNGE1MC05NDYyLTRkMjg5YzU5NDAxYTowMWY5OWIzMC1iMTdjLTQ5NmQtOGMxZi0yN2YyODIzYzkwMzQ=.jpg?width=1200&enable=upscale',
        },
        {
            id: 2,
            title: 'TITLE GOES HERE',
            // contents:
            //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit non nulla doloremque at dolorem libero ut, sequi nam explicabo iste maxime beatae, magnam facere aut fuga laudantium amet tenetur consectetur ',
            thumbnail: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsjuRz2_skbCKi1qlMAJre_MyrSIqFsx3C2rofKBCkBddQ8eLtkPHgkHHg9EUwIwp7Ayc&usqp=CAU',
        },
        {
            id: 3,
            title: 'TITLE GOES HERE',
            // contents:
            //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit non nulla doloremque at dolorem libero ut, sequi nam explicabo iste maxime beatae, magnam facere aut fuga laudantium amet tenetur consectetur ',
            thumbnail: 'https://i.pinimg.com/1200x/7b/4f/fd/7b4ffdec7e28d29fe2173ee0f7d9ba4a.jpg',
        },
        {
            id: 4,
            title: 'TITLE GOES HERE',
            // contents:
            //     'Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit non nulla doloremque at dolorem libero ut, sequi nam explicabo iste maxime beatae, magnam facere aut fuga laudantium amet tenetur consectetur ',
            thumbnail:
                'https://images.unsplash.com/photo-1616058106290-8ec871aef47d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8YmVhdXRpZnVsJTIwY2F0fGVufDB8fDB8fHww&w=1000&q=80',
        },
    ] as IPost[],
};
