/* eslint-disable @next/next/no-img-element */
import ThemeRegistry from '@/theme/ThemeRegistry';
import type { Metadata } from 'next';
import Favicon from '/public/favicon.ico';
import '../styles/globals.css';
import { Providers } from '@/redux/provider';
import { ToastProvider } from '@/providers';
import { InitState } from '@/components/pages';

export const metadata: Metadata = {
    title: 'Home page | Petfoster',
    description: 'Generated by create next app',
    icons: [{ rel: 'icon', url: Favicon.src }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <Providers>
                <ThemeRegistry>
                    <body>
                        <ToastProvider>
                            <InitState>{children}</InitState>
                        </ToastProvider>
                    </body>
                </ThemeRegistry>
            </Providers>
        </html>
    );
}
