/* eslint-disable @next/next/no-img-element */
import '../../styles/globals.css';
import type { Metadata } from 'next';
import Favicon from '/public/favicon.ico';
import { Banner, Header } from '@/components/common';
import Footer from '@/components/common/common-footer/Footer';

export const metadata: Metadata = {
    title: 'Home page | Petfoster',
    description: 'Generated by create next app',
    icons: [{ rel: 'icon', url: Favicon.src }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <>
            <Header />
            <Banner />
            <main className="">{children}</main>

            <Footer />
        </>
    );
}
